server.port=${PORT:8080}
spring.application.name=api-gateway

customer.service.url=${CUSTOMER_SERVICE_URL:http://localhost:8081}
order.service.url=${ORDER_SERVICE_URL:http://localhost:8082}

spring.cloud.gateway.server.webflux.routes[0].id=customer-service
spring.cloud.gateway.server.webflux.routes[0].uri=${customer.service.url}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/customers/**

spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=${order.service.url}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/orders/**

management.endpoints.web.exposure.include=health,info
