# Puerto del servicio
server.port=8081

# Nombre de la app
spring.application.name=customer-service

# DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Opcional (evita warnings)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect