# Puerto del servicio
server.port=${PORT:8082}

# Nombre de la app
spring.application.name=order-service

# DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}

spring.jpa.open-in-view=false

customer.service.url=${CUSTOMER_SERVICE_URL}

# Swagger configuration

swagger.server.url=${SWAGGER_SERVER_URL:http://localhost:8081}
swagger.server.description=${SWAGGER_SERVER_DESCRIPTION}

swagger.contact.email=${SWAGGER_CONTACT_EMAIL}
swagger.contact.name=${SWAGGER_CONTACT_NAME}
swagger.contact.url=${SWAGGER_CONTACT_URL}

swagger.licence.name=${SWAGGER_LICENCE_NAME}
swagger.licence.url=${SWAGGER_LICENCE_URL}

swagger.info.title=${SWAGGER_INFO_TITLE}
swagger.info.version=${SWAGGER_INFO_VERSION}
swagger.info.description=${SWAGGER_INFO_DESCRIPTION}
swagger.info.terms=${SWAGGER_INFO_TERMS}