# Puerto del servicio
server.port=8082

# Nombre de la app
spring.application.name=order-service

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=app_user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect